parameters:
#    learn_first.example.class: Learn\FirstBundle\Example

services:
#    learn_first.example:
#        class: %learn_first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
